131 add git repo massager
Exove/local-docker pull request #176
Opened 2020-04-20 14:23 UTC by rpsu

Adding git-repo-massage -command and using in during `./ld init` to reset the Git history (flatten to a single command).

The command checks we are on a different Git repo (not Exove/local-docker), and that the commit history does not have the know first commit of local-docker.

In other words; it does wipe your existing project master.

2020-04-20 14:24 UTC, rpsu commented
Fixes #131

2020-04-20 16:06 UTC, kekkis commented on docker/scripts/ld.command.git-repo-massage.sh
> +#            # Very simple test to see we have .git at the end of remote url.
Two comment markers, for any specific purpose?
```suggestion
             # Very simple test to see we have .git at the end of remote url.
```

2020-04-20 16:18 UTC, kekkis commented on docker/scripts/ld.command.git-repo-massage.sh
> +                echo -e "${Red}ERROR: Git repository address is invalid. Please try again.${Color_Off}"
Should this error specify that the validity is based on the fact that the URL ends in `.git`?

2020-04-20 16:19 UTC, kekkis commented on docker/scripts/ld.command.git-repo-massage.sh
> +        if [ ! -z "$ANSWER" ]; then
`! -z` == `-n` (again)

2020-04-20 16:28 UTC, kekkis commented on docker/scripts/ld.command.git-repo-massage.sh
> +                sleep 1
Not a huge fan of `sleep` personally.

2020-04-20 16:45 UTC, kekkis commented on docker/scripts/ld.command.git-repo-massage.sh
> +#    echo "Example: $SCRIPT_NAME_SHORT git-repo-massage FORCE # to ignore commit hash checks"
Is this commented-out line left in place on purpose?

2020-04-20 16:45 UTC, kekkis commented on docker/scripts/ld.command.git-repo-massage.sh
> +    GIT_REPO_MATCH=$(git config --get remote.origin.url | grep -c 'Exove/local-docker.git')
Should the regex end in `$` to reduce false positive matches?

2020-04-21 06:03 UTC, rpsu commented
> The commit message in the first commit sounds like you have squashed multiple commits and only left the last commit message in place. Am I correct in guessing this is the case? ;)

Seem so :/

2020-04-21 06:06 UTC, rpsu commented on docker/scripts/ld.command.git-repo-massage.sh
> +function ld_command_git-repo-massage_exec() {
multi-word commands do that all over the local-docker. While I don't see see it as a huge problem I am not against changing them either. Just thinking that for example Drush commands also use hyphens, not underscores, to separate words, yes?

2020-04-21 06:08 UTC, kekkis commented on docker/scripts/ld.command.git-repo-massage.sh
> +function ld_command_git-repo-massage_exec() {
Yes. To be clear: I don't suggest changing the names of the commands but the names of the functions (basically before calling a function "hook" we would replace `-` with `_`).

2020-04-21 06:09 UTC, rpsu commented on docker/scripts/ld.command.git-repo-massage.sh
> +                echo -e "${Red}ERROR: Git repository address is invalid. Please try again.${Color_Off}"
probably a good idea. I tried at first to do some regex magix to validate the URL, but Git accepts wide variety of URLs so I just ...gave up.

2020-04-21 06:09 UTC, rpsu commented on docker/scripts/ld.command.git-repo-massage.sh
> +        if [ ! -z "$ANSWER" ]; then
thank, duly noted 👍

2020-04-21 06:09 UTC, rpsu commented on docker/scripts/ld.command.git-repo-massage.sh
> +                sleep 1
I draw some attention with sleep here'n'there, but maybe it is not _that_ necessary here.

2020-04-21 06:10 UTC, rpsu commented on docker/scripts/ld.command.git-repo-massage.sh
> +#    echo "Example: $SCRIPT_NAME_SHORT git-repo-massage FORCE # to ignore commit hash checks"
yes, pending implementation of the `FORCE` parameter.

2020-04-21 06:10 UTC, rpsu commented on docker/scripts/ld.command.git-repo-massage.sh
> +    GIT_REPO_MATCH=$(git config --get remote.origin.url | grep -c 'Exove/local-docker.git')
Good idea.

2020-04-21 07:04 UTC, rpsu commented
I reworded the 1st commit in this branch and .. naturally all of your review comments are now off. 

However I think I caught all of the changes now.

2020-04-21 07:06 UTC, rpsu commented on docker/scripts/ld.command.git-repo-massage.sh
> +                sleep 1
removed

2020-04-21 07:07 UTC, rpsu commented on docker/scripts/ld.command.git-repo-massage.sh
> +function ld_command_git-repo-massage_exec() {
roger that. Perhaps a new issue out of that one?

2020-04-21 07:07 UTC, rpsu commented on docker/scripts/ld.command.git-repo-massage.sh
> +                echo -e "${Red}ERROR: Git repository address is invalid. Please try again.${Color_Off}"
updated instructions, and also added check that the url has no spaces.

2020-07-15 09:04 UTC, rpsu commented
Rebased against `master` HEAD

2020-07-15 09:37 UTC, rpsu commented
Rebased even more against `master`s `HEAD`

2020-09-04 05:16 UTC, kekkis requested changes

2020-09-04 05:16 UTC, kekkis commented on docker/scripts/ld.command.git-repo-massage.sh
> +    GIT_REPO_MATCH=$(git config --get remote.origin.url | egrep -c 'Exove\/local\-docker\.git$')
https://linux.die.net/man/1/egrep

> grep searches the named input FILEs (or standard input if no files are named, or if a single hyphen-minus (-) is given as file name) for lines containing a match to the given PATTERN. By default, grep prints the matching lines.
>
> In addition, two variant programs egrep and fgrep are available. egrep is the same as grep -E. fgrep is the same as grep -F. **Direct invocation as either egrep or fgrep** is deprecated, but is provided to allow historical applications that rely on them to run unmodified.

2020-09-04 05:16 UTC, kekkis commented on ld.sh
> +WHITELIST_COMMANDS=("help" "self-update" "init" "git-repo-massage")
Unrelated to this change but may be relevant - should we change from WHITELIST to ALLOWLIST, for example?

2020-09-04 05:16 UTC, kekkis commented on docker/scripts/ld.functions.sh
> +    while [ $WAIT -gt 0 ]; do
Since `$WAIT` can be anything at this point, should it be checked or forced into an integer'ish value before comparing to 0?

2020-09-04 07:07 UTC, rpsu commented on docker/scripts/ld.command.git-repo-massage.sh
> +    GIT_REPO_MATCH=$(git config --get remote.origin.url | egrep -c 'Exove\/local\-docker\.git$')
cool, fixed!

2020-09-04 07:13 UTC, rpsu commented on ld.sh
> +WHITELIST_COMMANDS=("help" "self-update" "init" "git-repo-massage")
Let's open another issue (=> #193 )  for this since this PR is is about `git-repo-massage` rather than renaming things across the application.

2020-09-04 07:28 UTC, rpsu commented on docker/scripts/ld.functions.sh
> +    while [ $WAIT -gt 0 ]; do
good point, thanks. Fixed - if you pass the solution :) 
`WAIT=$((${1:-5} + 0))`

2020-09-04 07:51 UTC, kekkis commented on docker/scripts/ld.functions.sh
> +    while [ $WAIT -gt 0 ]; do
I found https://stackoverflow.com/a/59781257/1268075 which points to using `printf`:
`int(){ printf '%d' ${1:-} 2>/dev/null || :; }` - but point 2 in that answer uses `expr` (or `(( ))`), just defaulting to empty string instead of our `5`. So I guess it's acceptable to use this version.

2020-09-04 07:51 UTC, kekkis approved these changes

2020-09-04 07:54 UTC, kekkis commented on docker/scripts/ld.command.git-repo-massage.sh
> +    GIT_REPO_MATCH=$(git config --get remote.origin.url | grep -e -c 'Exove\/local\-docker\.git$')
https://linux.die.net/man/1/egrep says to use `grep -E` (not `grep -e`) to replace `egrep`.

2020-09-04 10:16 UTC, merged

2020-09-04 10:16 UTC, rpsu commented
Fixes #131