Adding Drupal Solr core and default configuration
Exove/local-docker pull request #192
Opened 2020-08-11 13:10 UTC by jancho

- Creates Solr core with default configuration
- New ld command "solr-config-update" to copy fresh configuration files into the solr container and restart it

2020-08-31 05:55 UTC, rpsu requested changes

2020-08-31 05:55 UTC, rpsu commented on docker/docker-compose.common.yml
> +      - ./configs/solr:/solr-config
see comment on `docker/docker-compose.cached.yml`

2020-08-31 05:55 UTC, rpsu commented on docker/docker-compose.ddev.yml
> +      - ./configs/solr:/solr-config
see comment on `docker/docker-compose.cached.yml`

2020-08-31 05:55 UTC, rpsu commented on docker/docker-compose.nfs.yml
> +      - ./configs/solr:/solr-config
see comment on `docker/docker-compose.cached.yml`

2020-08-31 05:55 UTC, rpsu commented on docker/docker-compose.skeleton.yml
> +      - ./configs/solr:/solr-config
see comment on `docker/docker-compose.cached.yml`

2020-08-31 05:55 UTC, rpsu commented on docker/scripts/ld.command.solr-config-update.sh
> +}
I would be nice to have also `ld_command_solr-config-update-extended-help()` function with more verbose help.

2020-08-31 05:55 UTC, rpsu commented on docker/scripts/ld.command.solr-config-update.sh
> +    docker-compose exec ${CONTAINER_SOLR:-solr} bash -c "cp /solr-config/conf/* /var/solr/data/${SOLR_CORE}/conf"
what is the reason we copy the configs instead of using the folder on host mapped directly to `/var/solr/data/${SOLR_CORE}/conf`? Shell variable `${SOLR_CORE}` expands as part of the path name.

2020-08-31 05:56 UTC, rpsu commented
Overall very good PR, improves LD a lot for common Drupal projects. thanks already at this point @jancho  <3 !

2020-12-02 10:16 UTC, jancho commented on docker/docker-compose.cached.yml
> +      - ./configs/solr:/solr-config
Moved solr configs to `docker/configs/solr`

2020-12-02 10:16 UTC, jancho commented on docker/docker-compose.common.yml
> +      - ./configs/solr:/solr-config
Changes made

2020-12-02 10:16 UTC, jancho commented on docker/docker-compose.ddev.yml
> +      - ./configs/solr:/solr-config
Changes made

2020-12-02 10:16 UTC, jancho commented on docker/docker-compose.skeleton.yml
> +      - ./configs/solr:/solr-config
Changes made

2020-12-02 10:24 UTC, jancho commented on docker/scripts/ld.command.solr-config-update.sh
> +    docker-compose exec ${CONTAINER_SOLR:-solr} bash -c "cp /solr-config/conf/* /var/solr/data/${SOLR_CORE}/conf"
When solr core is first created, it's created with configs from `docker/configs/solr` This command can be used if config needs to be updated.
There were certain issues with sync (permissions if I remember correctly). But since solr configs updated don't happen very often I think this is sufficient solution.

2020-12-02 10:27 UTC, jancho commented on docker/scripts/ld.command.solr-config-update.sh
> +}
I think the current description explains what the command does pretty well.

2021-03-16 11:38 UTC, rpsu commented
Rebased, added extended help, added some checks (such as container is running and important values are set).

2021-03-16 11:38 UTC, rpsu approved these changes

2021-03-16 11:40 UTC, rpsu approved these changes

2021-03-16 11:41 UTC, merged